# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38efb2b24896bbafc65f79499637f995788c415bb26402525f0f35f7da7c190612d72c481c05c8e226e8df70782ee430721c01df7816c53b2cefc112f626a6dc
  stripe_publishable_key: pk_test_tytk70ysvSeUtTlilt49ozl2
  stripe_secret_key: sk_test_jlVB8fXKXyUCoTzfzxbs4EuW
test:
  secret_key_base: 8c289e7a437ea999b6abfdf476cbe901060506bbf5924543215a63bfca658f5b2fd149879857c5ce918f91f58783ed8aa8faa8ab4ac3edb6813177df86fa0229

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
